[Errno 2] No such file or directory: 'kusimused_vastused.txt'
Stack trace:
 >  File "C:\Users\opilane\source\repos\Bohatyrov\KüsimustikArturDombrovski\KüsimustikArturDombrovski.py", line 3, in loe_kusimused_vastused
 >    with open(failinimi, "r", encoding="utf-8") as fail:
 >  File "C:\Users\opilane\source\repos\Bohatyrov\KüsimustikArturDombrovski\KüsimustikArturDombrovski.py", line 53, in <module> (Current frame)
 >    kus_vas = loe_kusimused_vastused(failinimi)
Loaded '__main__'
Loaded 'runpy'
The program 'python.exe' has exited with code 0 (0x0).
